import { ImageGenerationParams } from "../types/index.js";
import { replicate } from "../services/replicate.js";
import { handleError } from "../utils/error.js";
import { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { FileOutput } from "replicate";
import { mimeFor, outputToBase64 } from "../utils/image.js";
import { resolveImageModelId } from "../utils/model.js";

export const registerGenerateImageTool = async (
  input: ImageGenerationParams
): Promise<CallToolResult> => {
  const { model_id, support_image_mcp_response_type, ...predictionInput } =
    input;
  try {
    const modelId = resolveImageModelId(model_id);
    const [output] = (await replicate.run(modelId, {
      input: predictionInput,
    })) as [FileOutput];
    const imageUrl = output.url() as unknown as string;
    const supportsImageContent = support_image_mcp_response_type !== false;

    const structuredContent = {
      url: imageUrl,
      prompt: input.prompt,
      format: input.output_format,
      aspect_ratio: input.aspect_ratio,
      ...(input.seed !== undefined ? { seed: input.seed } : {}),
    };

    const content: CallToolResult["content"] = [
      { type: "text", text: `Generated image URL: ${imageUrl}` },
    ];
    if (supportsImageContent) {
      content.push({
        type: "image",
        data: await outputToBase64(output),
        mimeType: mimeFor(input.output_format),
      });
    }
    content.push({
      type: "text",
      text: `Generated by Flux with prompt: ${input.prompt}`,
    });

    return {
      content,
      structuredContent,
    };
  } catch (error) {
    return handleError(error);
  }
};
