import { ImageGenerationParams } from "../types/index.js";
import { replicate } from "../services/replicate.js";
import { handleError } from "../utils/error.js";
import { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { FileOutput } from "replicate";
import { mimeFor, outputToBase64 } from "../utils/image.js";
import { CONFIG } from "../config/index.js";

export const registerGenerateImageTool = async (
  input: ImageGenerationParams
): Promise<CallToolResult> => {
  try {
    const [output] = (await replicate.run(CONFIG.imageModelId, {
      input,
    })) as [FileOutput];
    const imageUrl = output.url() as unknown as string;
    const imageBase64 = await outputToBase64(output);

    const structuredContent = {
      url: imageUrl,
      prompt: input.prompt,
      format: input.output_format,
      aspect_ratio: input.aspect_ratio,
      ...(input.seed !== undefined ? { seed: input.seed } : {}),
    };

    return {
      content: [
        { type: "text", text: `Generated image URL: ${imageUrl}` },
        {
          type: "image",
          data: imageBase64,
          mimeType: mimeFor(input.output_format),
        },
        {
          type: "text",
          text: `Generated by Flux Schnell with prompt: ${input.prompt}`,
        },
      ],
      structuredContent,
    };
  } catch (error) {
    return handleError(error);
  }
};
